
--- Project Lukman Alfaridzi RFM Analysis (Segmented Cusomer)

SELECT * FROM [dbo].[sales_data_sample]

-- CHECKING UNIQUE VALUES
SELECT DISTINCT STATUS FROM [dbo].[sales_data_sample]
SELECT DISTINCT YEAR_ID FROM[dbo].[sales_data_sample]
SELECT DISTINCT PRODUCTLINE FROM [dbo].[sales_data_sample]
SELECT DISTINCT COUNTRY FROM [dbo].[sales_data_sample]
SELECT DISTINCT DEALSIZE FROM [dbo].[sales_data_sample]
SELECT DISTINCT TERRITORY FROM [dbo].[sales_data_sample]
SELECT DISTINCT MONTH_ID FROM [dbo].[sales_data_sample]
WHERE YEAR_ID = 2003


--ANALYSIS REVENUE
SELECT PRODUCTLINE, SUM(sales) Revenue
FROM [dbo].[sales_data_sample]
GROUP BY PRODUCTLINE
ORDER BY 2 DESC

SELECT YEAR_ID, SUM(sales) Revenue
FROM [dbo].[sales_data_sample]
GROUP BY YEAR_ID
ORDER BY 2 DESC

SELECT DEALSIZE, SUM(sales) Revenue
FROM [dbo].[sales_data_sample]
GROUP BY DEALSIZE
ORDER BY 2 DESC

-- WHAT THE BEST MONTH FOR SALES IN A SPESIFIC YEAR? HOW MUCH WAS EARNED THAT MONTH
SELECT MONTH_ID, SUM(sales) Revenue, COUNT (ORDERNUMBER) Frequency
	FROM [dbo].[sales_data_sample]
	WHERE YEAR_ID = 2004
	GROUP BY MONTH_ID
ORDER BY 2 DESC

-- NOVEMBER SEEMS TO BE THE MONTH, WHAT PRODUCT THEY SELL IN NOVEMBER
SELECT MONTH_ID, PRODUCTLINE, SUM(sales) Revenue, COUNT(ORDERNUMBER) Frequency
	FROM [dbo].[sales_data_sample]
	WHERE YEAR_ID = 2004 AND MONTH_ID = 11
	GROUP BY MONTH_ID, PRODUCTLINE
ORDER BY 3 DESC

-- WHO IS BEST OUR CUSTOMER (RFM ANALYSIS)
;WITH RFM AS
(
SELECT CUSTOMERNAME,
SUM(sales) MONETARYVALUE,
AVG(sales) AVGMONETARYVALUE,
COUNT(ORDERNUMBER) FREQUENCY,
MAX(ORDERDATE)LAST_ORDER_DATE,
(SELECT MAX (ORDERDATE) FROM [dbo].[sales_data_sample]) MAX_ORDER_DATE,
DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX (ORDERDATE) FROM [dbo].[sales_data_sample])) RECENCY
FROM [dbo].[sales_data_sample]
GROUP BY CUSTOMERNAME
)
SELECT R.*,
NTILE(4) OVER (ORDER BY RECENCY DESC) RFM_RECENCY,
NTILE(4) OVER (ORDER BY FREQUENCY) RFM_FREQUENCY,
NTILE(4) OVER (ORDER BY AVGMONETARYVALUE) RFMMONETARY
FROM RFM R
ORDER BY 4 DESC


--#RFM ANALYSIS


DROP TABLE IF EXISTS #RFM
;WITH RFM AS
(
SELECT CUSTOMERNAME,
	SUM(sales) MONETARYVALUE,
	AVG(sales) AVGMONETARYVALUE,
	COUNT(ORDERNUMBER) FREQUENCY,
	MAX(ORDERDATE)LAST_ORDER_DATE,
	(SELECT MAX (ORDERDATE) FROM [dbo].[sales_data_sample]) MAX_ORDER_DATE,
	DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX (ORDERDATE) FROM [dbo].[sales_data_sample])) RECENCY
	FROM [dbo].[sales_data_sample]
	GROUP BY CUSTOMERNAME
),
RFM_CALC AS
(
SELECT R.*,
	NTILE(4) OVER (ORDER BY RECENCY DESC) RFM_RECENCY,
	NTILE(4) OVER (ORDER BY FREQUENCY) RFM_FREQUENCY,
	NTILE(4) OVER (ORDER BY MONETARYVALUE) RFM_MONETARY
FROM RFM R
) 
SELECT 
	C.*, RFM_RECENCY+ RFM_FREQUENCY+ RFM_MONETARY AS RFM_CELL,
	CAST(RFM_RECENCY AS VARCHAR) + CAST(RFM_FREQUENCY AS VARCHAR) + CAST(RFM_MONETARY AS VARCHAR)RFM_CELL_STRING 
INTO #RFM
FROM RFM_CALC C

SELECT * FROM #RFM
---SEGMENTED CUSTOMER

SELECT CUSTOMERNAME, RFM_RECENCY, RFM_FREQUENCY, RFM_MONETARY,
CASE 
	WHEN RFM_CELL_STRING IN (111,112,121,122,123,132,211,212,113,141) THEN 'LOST_CUSTOMER' -- lost customer
	WHEN RFM_CELL_STRING IN (133,134,143,244,334,343,344) THEN 'SLIPPING AWAY,CANNOT LOSE' -- Big spenders who haven't purchased lately
	WHEN RFM_CELL_STRING IN (311,411,331) THEN 'NEW_CUSTOMERS'
	WHEN RFM_CELL_STRING IN (222,223,233,332) THEN 'POTENTIAL_CUSTOMERS'
	WHEN RFM_CELL_STRING IN (323,333,321,422,332,432) THEN 'ACTIVE' -- (customers who buy often& recently, but at low proce points)
	WHEN RFM_CELL_STRING IN (433,434,443,444) THEN 'LOYAL'
END RFM_SEGMENT
FROM #RFM



--WHAT PRODUCT ARE MOST OFTEN SALES TOGETHER
--SELECT * FROM  [dbo].[sales_data_sample] WHERE ORDERNUMBER = 10411
SELECT DISTINCT OrderNumber, stuff(
	
	(SELECT ',' + PRODUCTCODE
	FROM [dbo].[sales_data_sample] P
	WHERE ORDERNUMBER IN
	(
		SELECT ORDERNUMBER 
		FROM ( 
			SELECT ORDERNUMBER, COUNT(*) RN
			FROM [dbo].[sales_data_sample]
			WHERE STATUS = 'Shipped'
			GROUP BY ORDERNUMBER
	)M
	WHERE RN = 3
	) 
	AND P.ORDERNUMBER = S.ORDERNUMBER
	FOR XML PATH ('')) 
	, 1, 1,'') ProductCodes

	FROM [dbo].[sales_data_sample] S
	ORDER BY 2 desc